import React, { useState, useContext } from 'react';
import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    ScrollView,
    Alert,
    ActivityIndicator,
    TextInput
} from 'react-native';
import { AuthContext } from '../AuthContext';
import { Theme } from '../theme';
import { ref, set } from 'firebase/database';
import { rtdb } from '../firebase';

export default function QRImportScreen({ navigation }) {
    const { user } = useContext(AuthContext);
    const [importData, setImportData] = useState('');
    const [isImporting, setIsImporting] = useState(false);

    const handleImport = async () => {
        if (!importData.trim()) {
            Alert.alert('Error', 'Please paste QR inventory JSON data');
            return;
        }

        setIsImporting(true);

        try {
            const products = JSON.parse(importData);
            let successCount = 0;
            let errorCount = 0;

            // Validate data structure
            if (!Array.isArray(products)) {
                throw new Error('Invalid format: Expected JSON array');
            }

            for (const product of products) {
                try {
                    // Validate required fields
                    if (!product.productCode || !product.name || !product.price) {
                        console.warn('Skipping invalid product:', product);
                        errorCount++;
                        continue;
                    }

                    const productRef = ref(rtdb, `users/${user.userId}/products/${product.productCode}`);
                    
                    await set(productRef, {
                        productCode: product.productCode,
                        name: product.name,
                        price: parseFloat(product.price),
                        wholesalePrice: parseFloat(product.wholesalePrice) || 0,
                        quantity: parseInt(product.quantity) || 1,
                        lowStockThreshold: parseInt(product.lowStockThreshold) || 10,
                        category: product.category || 'GENERAL',
                        manufactureDate: product.manufactureDate || '',
                        expiryDate: product.expiryDate || '',
                        userId: user.userId,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString()
                    });
                    
                    successCount++;
                    console.log(`✅ Imported: ${product.productCode}`);

                } catch (error) {
                    console.error(`Failed to import ${product.productCode}:`, error);
                    errorCount++;
                }
            }

            Alert.alert(
                'Import Complete',
                `Successfully imported ${successCount} products\nFailed: ${errorCount}`,
                [
                    {
                        text: 'OK',
                        onPress: () => {
                            setImportData('');
                            navigation.goBack();
                        }
                    }
                ]
            );

        } catch (error) {
            Alert.alert(
                'Import Error', 
                error.message.includes('JSON') 
                    ? 'Invalid JSON format. Please check your data.'
                    : 'Import failed. Please try again.'
            );
            console.error('Import error:', error);
        } finally {
            setIsImporting(false);
        }
    };

    const showFormatInstructions = () => {
        Alert.alert(
            'QR Import Format',
            `Expected JSON format from your Python script:

[
  {
    "productCode": "RAPIDENE-001",
    "name": "Rapidene 500mg",
    "price": 150.00,
    "wholesalePrice": 120.00,
    "quantity": 1,
    "lowStockThreshold": 10,
    "category": "PHARMA",
    "manufactureDate": "2025-07-15",
    "expiryDate": "2027-01-15"
  }
]

Copy the entire content from inventory_import.json`,
            [{ text: 'OK' }]
        );
    };

    return (
        <ScrollView style={styles.container}>
            <Text style={styles.header}>QR Inventory Import</Text>
            
            <Text style={styles.description}>
                Paste the JSON data generated by your Python QR code script to import products.
            </Text>

            <TouchableOpacity 
                style={styles.helpButton}
                onPress={showFormatInstructions}
            >
                <Text style={styles.helpButtonText}>📋 View Expected Format</Text>
            </TouchableOpacity>

            <TextInput
                style={styles.textInput}
                value={importData}
                onChangeText={setImportData}
                placeholder="Paste JSON data from inventory_import.json here..."
                multiline
                numberOfLines={12}
                textAlignVertical="top"
                placeholderTextColor="#999"
            />

            <TouchableOpacity 
                style={[styles.importButton, isImporting && styles.disabledButton]}
                onPress={handleImport}
                disabled={isImporting}
            >
                {isImporting ? (
                    <View style={styles.loadingContainer}>
                        <ActivityIndicator color="white" size="small" />
                        <Text style={styles.importButtonText}>Importing...</Text>
                    </View>
                ) : (
                    <Text style={styles.importButtonText}>Import Products to Inventory</Text>
                )}
            </TouchableOpacity>

            <View style={styles.workflow}>
                <Text style={styles.workflowTitle}>📋 Correct Workflow:</Text>
                
                <View style={styles.step}>
                    <Text style={styles.stepNumber}>1</Text>
                    <Text style={styles.stepText}>
                        Run your Python QR generator script
                    </Text>
                </View>
                
                <View style={styles.step}>
                    <Text style={styles.stepNumber}>2</Text>
                    <Text style={styles.stepText}>
                        Open generated inventory_import.json file
                    </Text>
                </View>
                
                <View style={styles.step}>
                    <Text style={styles.stepNumber}>3</Text>
                    <Text style={styles.stepText}>
                        Copy ALL content and paste above
                    </Text>
                </View>
                
                <View style={styles.step}>
                    <Text style={styles.stepNumber}>4</Text>
                    <Text style={styles.stepText}>
                        Click "Import Products to Inventory"
                    </Text>
                </View>
                
                <View style={styles.step}>
                    <Text style={styles.stepNumber}>5</Text>
                    <Text style={styles.stepText}>
                        Print QR codes and start scanning in web POS!
                    </Text>
                </View>
            </View>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f7f7f7',
    },
    header: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#333',
        textAlign: 'center',
    },
    description: {
        fontSize: 16,
        color: '#666',
        marginBottom: 20,
        textAlign: 'center',
        lineHeight: 22,
    },
    helpButton: {
        backgroundColor: '#6c757d',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginBottom: 15,
    },
    helpButtonText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 14,
    },
    textInput: {
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 10,
        padding: 15,
        fontSize: 14,
        minHeight: 200,
        marginBottom: 20,
        textAlignVertical: 'top',
        fontFamily: 'monospace',
    },
    importButton: {
        backgroundColor: Theme.colors.primary,
        padding: 16,
        borderRadius: 10,
        alignItems: 'center',
        marginBottom: 25,
    },
    disabledButton: {
        backgroundColor: '#ccc',
    },
    loadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    importButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    workflow: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        borderLeftWidth: 4,
        borderLeftColor: Theme.colors.primary,
    },
    workflowTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 15,
        color: '#333',
    },
    step: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    stepNumber: {
        backgroundColor: Theme.colors.primary,
        color: 'white',
        width: 24,
        height: 24,
        borderRadius: 12,
        textAlign: 'center',
        lineHeight: 24,
        fontWeight: 'bold',
        marginRight: 12,
        marginTop: 2,
    },
    stepText: {
        flex: 1,
        fontSize: 14,
        color: '#666',
        lineHeight: 20,
    },
});